server:
  port: 8083

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      mvc:
       routes:
        - id: POST
          uri: lb://POST
          predicates:
            - Path=/api/v1/posts/**
        - id: COMMENT
          uri: lb://COMMENT
          predicates:
            - Path=/api/v1/comments/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka






